import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import ReactDOM from 'react-dom'
import { ICategory } from '../types'

import http from '../services/http-common'
import styles from '../styles/Home.module.css'
import Category from '../components/category'
import Modal from '../components/modal'



const Home: NextPage = () => {
  const [ballots, setBallots] = useState<ICategory[]>([]);
  const [list, setList] = useState<string[]>([]);
  const [modal, setModal] = useState(false);

  const onSelect = (item_id: string) => {
    if (list.some(el => el === item_id)) {
      setList([...list.filter(el => el !== item_id)])
    } else
      setList([...list, item_id])
  }




  useEffect(() => {
    async function fetchBallot() {
      const response = await http.get('/ballots');
      console.log(response.data.items);
      if (response && response.data) setBallots(response.data.items)
    }

    fetchBallot();
  }, []);

  return (
    <div className={`${styles.container} ${modal && styles.modalopen}`} id="container">
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.subject}>AWORDS 2021</h2>
        {ballots && ballots.map((ballot: ICategory) =>
          <Category key={ballot.id} data={ballot} onSelect={onSelect} selected={list} />
        )}

        <div className={styles.button} onClick={() => setModal(true)}>Submit Ballots</div>
      </main >
      {modal && ReactDOM.createPortal(
        <Modal onClose={() => setModal(false)} selected={list} />,
        document.getElementById('container') as HTMLInputElement
      )}
    </div >
  )
}

export default Home
